# Generated by Django 5.2.8 on 2025-12-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('asset_type', models.CharField(choices=[('STOCKS_KR', 'Stocks_KR'), ('STOCKS_GLB', 'Stocks_GLB'), ('BONDS_KR', 'Bonds_KR'), ('BONDS_GLB', 'Bonds_GLB'), ('FUNDS', 'Funds'), ('ALTERNATIVES', 'Alternatives'), ('CASH', 'Cash')], max_length=32)),
                ('currency', models.CharField(default='KRW', max_length=10)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'asset',
                'indexes': [models.Index(fields=['asset_type', 'is_enabled'], name='asset_asset_t_f593bb_idx')],
            },
        ),
    ]
