"""
Django settings for aim_fin project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ, os
from datetime import timedelta

# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = Path(__file__).resolve().parent.parent.parent
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

SECRET_KEY = env("SECRET_KEY", default="dev-secret-change-me")
DEBUG = env.bool("DEBUG", default=True)
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])



# Application definition

INSTALLED_APPS = [
    "users",
    "assets",
    "portfolios",
    "analysis",
    "common",
    
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "csp",

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# 기본 Authorization 헤더로 진행(나중에 쿠키 기반으로 바꿀 수 있음)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "users.auth.CookieJWTAuthentication",                 # 쿠키 우선
        "rest_framework_simplejwt.authentication.JWTAuthentication",  # 헤더(Bearer)도 허용
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

MIDDLEWARE = [
    # CSP는 가능하면 맨 앞 (보안 헤더 먼저)
    "csp.middleware.CSPMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # corsheaders는 여기!
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aim_fin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aim_fin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': env.db('DATABASE_URL', default=f'sqlite:///{BASE_DIR / "db.sqlite3"}')
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SimpleJWT 토큰 수명 (쿠키/헤더 어떤 방식이든 공통)
from datetime import timedelta
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,               # 리프레시 회전
    "BLACKLIST_AFTER_ROTATION": True,            # 회전 후 이전 리프레시 무효화
    "UPDATE_LAST_LOGIN": True,
}

# CORS (개발용/배포용 공통)
CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[
    "http://localhost:5173",
    "http://127.0.0.1:5173",
])
CORS_ALLOW_CREDENTIALS = True

# CSRF
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[
    "http://localhost:5173",
    "http://127.0.0.1:5173",
])

# CSP (최소 화이트리스트. 필요한 SDK만 추가)
# ✅ django-csp v4 포맷
CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        # 기본 출처
        "default-src": ("'self'",),

        # 스크립트: 필요한 SDK 도메인만 화이트리스트
        "script-src": (
            "'self'",
            "https://accounts.google.com",
            # 개발 중 인라인 스크립트가 꼭 필요하면 다음 중 하나를 사용 (권장하진 않음)
            # "'unsafe-inline'",  # 지양
            # "'nonce-<RUNTIME_NONCE>'",  # 런타임 nonce 적용 시
        ),

        # 스타일/폰트/이미지
        "style-src": ("'self'", "https://fonts.googleapis.com"),
        "font-src": ("'self'", "https://fonts.gstatic.com"),
        "img-src": ("'self'", "data:"),

        # API 통신(프론트 개발 서버/Vite와 백엔드)
        # Vue 개발서버 쓰면 connect-src에 추가
        "connect-src": (
            "'self'",
            "http://localhost:5173",
            "http://127.0.0.1:5173",
        ),

    },
}
# Redis 캐시/세션 (django-redis)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    }
}
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"


SPECTACULAR_SETTINGS = {
    'TITLE': 'AImFin API',
    'DESCRIPTION': 'Internal API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,  # /api/docs/에서 /api/schema/ 직접 호출하므로 보통 False
}

SPECTACULAR_SETTINGS.update({
    'SWAGGER_UI_DIST': 'SIDECAR',  # CDN 대신 로컬 정적 파일 사용
})


AUTH_USER_MODEL = "users.User"

# OAuth/프런트 URL (소셜 로그인용)
BASE_URL = env("BASE_URL", default="http://localhost:8000")
FRONTEND_URL = env("FRONTEND_URL", default="http://localhost:5173")
GOOGLE_CLIENT_ID = env("GOOGLE_CLIENT_ID", default="")
GOOGLE_CLIENT_SECRET = env("GOOGLE_CLIENT_SECRET", default="")
# ... 기존 import/environ 세팅 하단
KAKAO_CLIENT_ID = env("KAKAO_CLIENT_ID", default="")
KAKAO_CLIENT_SECRET = env("KAKAO_CLIENT_SECRET", default="")
KAKAO_REDIRECT_URI = env("KAKAO_REDIRECT_URI", default="http://localhost:8000/api/users/auth/kakao/callback")


# --- LLM/GMS 설정 (기존 변수와 호환) ---
OPENAI_MODEL   = env("OPENAI_MODEL",   default="gpt-4o-realtime-preview-2024-10-01")
OPENAI_TIMEOUT = env.int("OPENAI_TIMEOUT", default=30)

GMS_BASE_URL = env("GMS_BASE_URL", default="https://gms.ssafy.io/gmsapi")
GMS_KEY      = env("GMS_KEY",      default="")

# 통합 alias (gpt_client가 이 값만 참조)
AI_API_STYLE  = env("AI_API_STYLE",  default="responses")  # 'responses' 또는 'chat'
AI_MODEL      = env("AI_MODEL",      default=OPENAI_MODEL)
AI_TIMEOUT    = env.int("AI_TIMEOUT", default=OPENAI_TIMEOUT)

# GMS 게이트웨이는 /api.openai.com/v1 붙여서 프록시됨
AI_API_BASE   = env(
    "AI_API_BASE",
    default=f"{GMS_BASE_URL.rstrip('/')}/api.openai.com/v1"
)
AI_API_KEY    = env("AI_API_KEY", default=GMS_KEY)