# Generated by Django 5.2.8 on 2025-12-11 04:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_json', models.JSONField(default=dict)),
                ('total_score', models.DecimalField(decimal_places=2, help_text='0.00 ~ 100.00', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('profile', models.CharField(choices=[('CONSERVATIVE', '안정형'), ('MODERATE_CONSERVATIVE', '안정추구형'), ('BALANCED', '중립형'), ('GROWTH', '적극투자형'), ('AGGRESSIVE', '공격투자형')], help_text='리스크 성향 코드', max_length=32)),
                ('section_scores', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'survey_result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRiskSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latest_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='as_current_for', to='users.surveyresult')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_snapshot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_risk_snapshot',
            },
        ),
        migrations.AddIndex(
            model_name='surveyresult',
            index=models.Index(fields=['user', '-created_at'], name='survey_resu_user_id_678f94_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresult',
            index=models.Index(fields=['profile'], name='survey_resu_profile_ab7387_idx'),
        ),
        migrations.AddConstraint(
            model_name='surveyresult',
            constraint=models.CheckConstraint(condition=models.Q(('total_score__gte', 0), ('total_score__lte', 100)), name='survey_result_total_score_0_100'),
        ),
    ]
