# Generated by Django 5.2.8 on 2025-12-11 07:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_surveyresult_userrisksnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_krw', models.DecimalField(decimal_places=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('horizon_code', models.CharField(choices=[('LT_1Y', '1년 이하'), ('Y_1_3', '1~3년'), ('Y_3_5', '3~5년'), ('GTE_5Y', '5년 이상')], max_length=16)),
                ('include_products', models.JSONField(default=list)),
                ('raw_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferences', to='users.surveyresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investment_preference',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferenceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latest_pref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='as_current_pref_for', to='users.investmentpreference')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference_snapshot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_preference_snapshot',
            },
        ),
        migrations.AddIndex(
            model_name='investmentpreference',
            index=models.Index(fields=['user', '-created_at'], name='investment__user_id_76d6cc_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentpreference',
            index=models.Index(fields=['horizon_code'], name='investment__horizon_e546b6_idx'),
        ),
    ]
