# Generated by Django 5.2.8 on 2025-12-15 09:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('source', models.CharField(choices=[('AI', 'AI'), ('MANUAL', 'MANUAL')], default='AI', max_length=12)),
                ('amount_krw', models.BigIntegerField()),
                ('profile', models.CharField(choices=[('CONSERVATIVE', '안정형'), ('MODERATE_CONSERVATIVE', '안정추구형'), ('BALANCED', '중립형'), ('GROWTH', '적극투자형'), ('AGGRESSIVE', '공격투자형')], max_length=32)),
                ('profile_label', models.CharField(max_length=64)),
                ('horizon_desc', models.CharField(max_length=64)),
                ('must_buckets', models.JSONField(default=list)),
                ('corrections', models.JSONField(blank=True, default=list)),
                ('allocations', models.JSONField(default=list)),
                ('metrics', models.JSONField(default=dict)),
                ('rationale', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('risks', models.TextField(blank=True, default='')),
                ('is_representative', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(choices=[('STOCKS_KR', 'Stocks_KR'), ('STOCKS_GLB', 'Stocks_GLB'), ('BONDS_KR', 'Bonds_KR'), ('BONDS_GLB', 'Bonds_GLB'), ('FUNDS', 'Funds'), ('ALTERNATIVES', 'Alternatives'), ('CASH', 'Cash')], max_length=32)),
                ('weight_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_rows', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['bucket'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('weight_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='portfolios.portfolioallocation')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_return_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_rec', to='portfolios.portfolio')),
            ],
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(condition=models.Q(('is_representative', True)), fields=('user',), name='unique_representative_per_user'),
        ),
        migrations.AddIndex(
            model_name='portfolioallocation',
            index=models.Index(fields=['portfolio', 'bucket'], name='portfolios__portfol_f9bd87_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioallocation',
            unique_together={('portfolio', 'bucket')},
        ),
        migrations.AddIndex(
            model_name='portfolioasset',
            index=models.Index(fields=['allocation', 'code'], name='portfolios__allocat_b8a33a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioasset',
            unique_together={('allocation', 'code')},
        ),
    ]
