# Generated by Django 5.2.8 on 2025-12-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='source',
        ),
    ]
