# Generated by Django 5.2.8 on 2025-12-22 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_remove_portfolio_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='risks',
        ),
    ]
