# Generated by Django 5.2.8 on 2025-12-23 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_remove_portfolio_risks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioAllocation',
        ),
        migrations.DeleteModel(
            name='PortfolioAsset',
        ),
        migrations.DeleteModel(
            name='PortfolioMetrics',
        ),
    ]
